<?php

namespace App\Models;

use App\Core\Support\Settings;
use App\Enums\GeneralSettingEnum;
use App\Traits\HasTranslationTrait;
use Illuminate\Database\Eloquent\Casts\Attribute;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;
use Spatie\Translatable\HasTranslations;

class GeneralSetting extends BaseModel implements HasMedia
{
    use InteractsWithMedia, HasTranslations;

    public array $translatable = [
        "title",
        "description",
        "content",
        "address",
        "name",
        "meta_tags",
        "feature_1",
        "feature_2",
        "feature_3",
        "feature_4",
        "feature_5",
        'privacy',
        'banner_1_text',
        'banner_2_text',
        'banner_3_text',
        'banner_4_text',
        'banner_1_desc',
        'banner_2_desc',
        'banner_3_desc',
        'banner_4_desc',
    ];

    public function registerMediaCollections(): void
    {
        $this->addMediaCollection(GeneralSettingEnum::LOGO_COLLECTION->name)->singleFile();
        $this->addMediaCollection(GeneralSettingEnum::USER_DEFAULT_IMAGE->name)->singleFile();

        $this->addMediaCollection('home1')->singleFile();
        $this->addMediaCollection('home2')->singleFile();
        $this->addMediaCollection('home3')->singleFile();
        $this->addMediaCollection('home4')->singleFile();

        $this->addMediaCollection('favicon')->singleFile();
    }

    public function siteLogo(): Attribute
    {
        return Attribute::get(function () {

            return $this->getFirstMediaUrl(GeneralSettingEnum::LOGO_COLLECTION->name);

        });
    }

    public function favicon(): Attribute
    {
        return Attribute::get(function () {

            return $this->getFirstMediaUrl('favicon');

        });
    }

    public function getBannerLink($bannerNum)
    {
        $productAtt = "banner_".$bannerNum."_product";
        $linkAtt    = "banner_".$bannerNum."_link";

        if($this->$productAtt != null){
            $product = Product::query()->find($this->$productAtt);
            if($product){
                return route('web.product.show',['slug' => $product?->slug]);
            }
            
        }elseif($this->$linkAtt != null){
            return $this->$linkAtt;
        }

        return '#';
    }

    public function userProfileImage(): Attribute
    {
        return Attribute::get(function () {

            return $this->getFirstMediaUrl(GeneralSettingEnum::USER_DEFAULT_IMAGE->name);

        });
    }


    protected static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::updated(function () {

            Settings::deleteCache();

        });
    }
}
